"""Ship the inference code to Kaggle and push the submission notebook.

    python -m src.kernel push --config conf/baseline.yaml

This is a code competition, so the deliverable is a notebook Kaggle reruns against
a hidden test set. The workspace rule is that `src/` must be importable from a
Kaggle notebook and that notebooks are for looking, not for producing submissions.
Both are satisfied by shipping `src/` and `conf/` as a Kaggle **dataset** and
keeping the notebook to a handful of lines that import and call it.

The rerun has no internet, so the dataset is the only way code gets in. It also
means the notebook must not import anything absent from the Kaggle image:
`tracksdata`, `geff` and `zarr` are all missing, which is why `src.predict` avoids
them and `src.data` falls back to tensorstore.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

from src.config import REPO_ROOT, load_config

DATASET_SLUG = "cell-tracking-src"
KERNEL_SLUG = "cell-tracking-inference"

ARCHIVE_NAME = "cellmot_src.zip"

# The 50-epoch training of the architecture the organisers released. Public and
# freely available, so within the rules on pretrained models. It also carries the
# offline wheels, which is the only way tracksdata and pyscipopt reach a rerun
# with no internet.
PACK_SLUG = "srcA/biohub-tracking-support-pack-50ep-v1"

# Emitted only for a learned-detector config. The local-max path needs none of
# this and must keep booting on a CPU kernel with nothing installed.
UNET_PRELUDE = '''
def find_pack_dir():
    """Locate the support pack under /kaggle/input, whatever the mount layout."""
    for root, dirs, _ in os.walk("/kaggle/input"):
        if os.path.isfile(os.path.join(root, "repo", "scripts",
                                       "predict_unet_transformer.py")):
            return root
        dirs[:] = [d for d in dirs if d != "competitions"]
    raise SystemExit("support pack not attached: expected " + PACK_SLUG)


PACK = find_pack_dir()
print("pack dir:", PACK)
os.environ["CELLMOT_PACK_DIR"] = PACK

# No internet in the rerun, so dependencies come from the pack's own wheels.
import subprocess

# ilpy is listed explicitly rather than left to resolve as a dependency of
# tracksdata. The ILP linker fails without it, and a resolver that quietly
# decides it is optional would surface as a crash 3 hours into a 12 hour rerun.
subprocess.run(
    ["pip", "install", "--no-index", "--find-links", os.path.join(PACK, "wheels"),
     "tracksdata", "zarr>=3.0.10", "pyscipopt", "ilpy"],
    check=True,
)

# Fail now, in the first seconds, rather than after inference has run. A rerun
# that dies at the linking step has already spent the GPU hours.
import importlib

for _mod in ("tracksdata", "ilpy", "pyscipopt"):
    importlib.import_module(_mod)
print("solver imports ok")
'''

NOTEBOOK_TEMPLATE = '''"""Inference for {competition}. Generated by src/kernel.py, do not edit here.

Config: {config_name} ({config_hash})
"""

import os
import sys

PACK_SLUG = "{pack_slug}"

# The code is uploaded as a zip, which Kaggle expands on ingest, so the dataset
# root already holds src/ and conf/ as directories and can go straight on the
# path. An attached dataset is the only way code gets in: the rerun has no
# internet, so there is no installing anything.
def find_code_dir():
    """Locate the directory holding src/predict.py under /kaggle/input.

    The mount layout is not stable across Kaggle's own conventions: datasets have
    turned up at both /kaggle/input/<slug> and /kaggle/input/datasets/<user>/<slug>.
    Searching for the file we actually need is immune to that, and to anyone
    renaming the dataset later.
    """
    candidates = [
        "/kaggle/input/{dataset_slug}",
        "/kaggle/input/datasets/{user}/{dataset_slug}",
    ]
    for path in candidates:
        if os.path.isfile(os.path.join(path, "src", "predict.py")):
            return path
    for root, dirs, _ in os.walk("/kaggle/input"):
        if os.path.isfile(os.path.join(root, "src", "predict.py")):
            return root
        # The competition data is tens of thousands of files; never descend it.
        dirs[:] = [d for d in dirs if d != "competitions"]
    raise SystemExit(
        "could not find src/predict.py under /kaggle/input. "
        "Is the code dataset attached to this notebook?"
    )


CODE = find_code_dir()
print("code dir:", CODE)
sys.path.insert(0, CODE)

os.environ.setdefault(
    "CELLMOT_DATA_DIR",
    "/kaggle/input/competitions/{competition}",
)

{prelude}
from src.predict import run

run(
    config_path=os.path.join(CODE, "conf", "{config_file}"),
    out_path="/kaggle/working/submission.csv",
)
'''


def _kaggle(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, "-m", "kaggle", *args], capture_output=True, text=True
    )


def _username() -> str:
    """The account name, taken from whatever credential form is configured."""
    from kaggle.api.kaggle_api_extended import KaggleApi

    api = KaggleApi()
    api.authenticate()
    name = (getattr(api, "config_values", {}) or {}).get("username")
    if name:
        return name
    # Access-token auth does not expose the username locally, so ask the API.
    r = _kaggle("config", "view")
    for line in r.stdout.splitlines():
        if "username" in line.lower():
            return line.split(":")[-1].strip()
    raise SystemExit("could not determine the Kaggle username")


def stage_dataset(staging: Path, user: str, cfg) -> Path:
    """Zip src/ and conf/ into a staging dir with dataset metadata.

    A single zip at the dataset root, because Kaggle datasets flatten directories
    and a package needs its tree intact. `src/metrics.py` is excluded on purpose:
    it imports tracksdata, which is not installed on Kaggle, and nothing in the
    inference path should be able to reach it.
    """
    if staging.exists():
        shutil.rmtree(staging)
    staging.mkdir(parents=True)

    with zipfile.ZipFile(
        staging / ARCHIVE_NAME, "w", zipfile.ZIP_DEFLATED
    ) as zf:
        for name in sorted(os.listdir(REPO_ROOT / "src")):
            if name.endswith(".py") and name != "metrics.py":
                zf.write(REPO_ROOT / "src" / name, f"src/{name}")
        for name in sorted(os.listdir(REPO_ROOT / "conf")):
            if name.endswith((".yaml", ".yml")):
                zf.write(REPO_ROOT / "conf" / name, f"conf/{name}")
        # The leave-one-embryo-out splits, needed by a training kernel. Without
        # this file the reference trainer silently falls back to its seeded
        # 90/10 shuffle over all 199 videos, which puts crops of the same embryo
        # on both sides and is the exact measurement the retrain exists to
        # avoid. A missing file must therefore be loud, and it is checked for in
        # the training template rather than left to fail quietly here.
        splits = REPO_ROOT / "data" / "meta" / "dataset_splits.json"
        if splits.exists():
            zf.write(splits, "meta/dataset_splits.json")

    (staging / "dataset-metadata.json").write_text(
        json.dumps(
            {
                "title": DATASET_SLUG,
                "id": f"{user}/{DATASET_SLUG}",
                "licenses": [{"name": "CC0-1.0"}],
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    return staging


def push_dataset(staging: Path, user: str, message: str) -> None:
    exists = _kaggle("datasets", "status", f"{user}/{DATASET_SLUG}").returncode == 0
    if exists:
        print(f"updating dataset {user}/{DATASET_SLUG}")
        r = _kaggle("datasets", "version", "-p", str(staging), "-m", message)
    else:
        print(f"creating dataset {user}/{DATASET_SLUG}")
        r = _kaggle("datasets", "create", "-p", str(staging))
    print((r.stdout or r.stderr).strip())
    if r.returncode != 0:
        raise SystemExit("dataset push failed")


def _is_unet(cfg) -> bool:
    """A learned-detector config needs a GPU, the pack, and its wheels."""
    return str((cfg.detect or {}).get("backend", "localmax")) == "unet"


def push_kernel(staging: Path, user: str, cfg, competition: str) -> str:
    kdir = staging.parent / "kernel"
    if kdir.exists():
        shutil.rmtree(kdir)
    kdir.mkdir(parents=True)

    (kdir / "inference.py").write_text(
        NOTEBOOK_TEMPLATE.format(
            competition=competition,
            config_name=cfg.name,
            config_hash=cfg.hash(),
            config_file=Path(cfg.path).name,
            dataset_slug=DATASET_SLUG,
            archive=ARCHIVE_NAME,
            user=user,
            pack_slug=PACK_SLUG,
            prelude=UNET_PRELUDE if _is_unet(cfg) else "",
        ),
        encoding="utf-8",
    )
    (kdir / "kernel-metadata.json").write_text(
        json.dumps(
            {
                "id": f"{user}/{KERNEL_SLUG}",
                "title": KERNEL_SLUG,
                "code_file": "inference.py",
                "language": "python",
                "kernel_type": "script",
                "is_private": True,
                "enable_gpu": _is_unet(cfg),
                "enable_tpu": False,
                # Must stay false: the rerun disables internet, and a kernel that
                # only works with it on will fail exactly when it matters.
                "enable_internet": False,
                "competition_sources": [competition],
                "dataset_sources": (
                    [f"{user}/{DATASET_SLUG}"]
                    + ([PACK_SLUG] if _is_unet(cfg) else [])
                ),
                "kernel_sources": [],
                "model_sources": [],
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    # `enable_gpu` alone gets a P100, and this competition refuses to accept a
    # submission from a P100 notebook ("Your Notebook cannot use P100 GPUs in
    # this competition"). The accelerator is not a metadata field, so it has to
    # be passed on the push. Valid values: NvidiaTeslaT4, NvidiaTeslaP100,
    # Tpu1VmV38.
    push_args = ["kernels", "push", "-p", str(kdir)]
    if _is_unet(cfg):
        push_args += ["--accelerator", "NvidiaTeslaT4"]
    r = _kaggle(*push_args)
    print((r.stdout or r.stderr).strip())
    if r.returncode != 0:
        raise SystemExit("kernel push failed")
    return f"https://www.kaggle.com/code/{user}/{KERNEL_SLUG}"



TRAIN_SLUG = "cell-tracking-train"

TRAIN_TEMPLATE = '''"""Embryo-disjoint training for {competition}. Generated by src/kernel.py.

Fold {split} of leave-one-embryo-out. Do not edit here.

Why from scratch and not from the support pack's weights. The pack was trained on
180 of the 199 training videos, drawn from BOTH embryos. Initialising from it
would put the held-out embryo's images into the model before the first step, which
is the leak this whole run exists to remove. `--unet-weights` is therefore not
passed, and that is deliberate rather than an omission.
"""

import json
import os
import subprocess
import sys
import time

PACK_SLUG = "{pack_slug}"


def find_pack_dir():
    for root, dirs, _ in os.walk("/kaggle/input"):
        if os.path.isdir(os.path.join(root, "repo", "scripts")):
            return root
        dirs[:] = [d for d in dirs if d != "competitions"]
    raise SystemExit("support pack not attached: expected " + PACK_SLUG)


def find_code_dir():
    for root, dirs, _ in os.walk("/kaggle/input"):
        if os.path.isfile(os.path.join(root, "meta", "dataset_splits.json")):
            return root
        dirs[:] = [d for d in dirs if d != "competitions"]
    raise SystemExit("code dataset with meta/dataset_splits.json not attached")


PACK = find_pack_dir()
CODE = find_code_dir()
SPLITS = os.path.join(CODE, "meta", "dataset_splits.json")
print("pack:", PACK, flush=True)
print("code:", CODE, flush=True)

subprocess.run(
    ["pip", "install", "--no-index", "--find-links", os.path.join(PACK, "wheels"),
     "tracksdata", "zarr>=3.0.10", "pyscipopt", "ilpy"],
    check=True,
)

sys.path.insert(0, os.path.join(PACK, "repo", "src"))
sys.path.insert(0, os.path.join(PACK, "repo", "scripts"))

DATA = "/kaggle/input/competitions/{competition}/train"
os.environ["CELLMOT_DATA_DIR"] = "/kaggle/input/competitions/{competition}"

# Guard the thing that silently invalidates the run. The trainer accepts a
# missing splits file by falling back to random.Random(0) over all videos, so an
# absent or malformed file would produce a plausible model measuring the wrong
# thing.
folds = json.loads(open(SPLITS).read())
fold = [f for f in folds if int(f["split"]) == {split}]
if not fold:
    raise SystemExit("no fold {split} in " + SPLITS)
fold = fold[0]
train_stems, test_stems = fold["train"], fold["test"]
emb = lambda n: n.split("_")[0]
overlap = {{emb(a) for a in train_stems}} & {{emb(b) for b in test_stems}}
if overlap:
    raise SystemExit(f"fold {split} is not embryo-disjoint: {{overlap}}")
print(f"fold {split}: {{len(train_stems)}} train videos "
      f"({{sorted({{emb(a) for a in train_stems}})}}), "
      f"{{len(test_stems)}} test ({{sorted({{emb(b) for b in test_stems}})}})",
      flush=True)

import torch
print("cuda:", torch.cuda.is_available(), torch.cuda.get_device_name(0)
      if torch.cuda.is_available() else "", flush=True)

sys.argv = [
    "train_unet_transformer.py",
    "--data-dir", DATA,
    "--splits", SPLITS,
    "--split", "{split}",
    "--epochs", "{epochs}",
    "--batch-size", "{batch_size}",
    "--num-workers", "2",
    "--window-size", "2",
    "--downsample", "1,4,4",
    "--pool-kernel-um", "5.0",
    "--single-gpu",
] + ({max_iters_arg})

t0 = time.time()
import train_unet_transformer
train_unet_transformer.main()
print("total minutes:", round((time.time() - t0) / 60, 1), flush=True)

# Copy whatever the trainer saved into /kaggle/working so it survives as output.
import shutil
from pathlib import Path

for pth in Path("/kaggle").rglob("edge_predictor_best.pth"):
    if "working" in str(pth):
        continue
    dest = Path("/kaggle/working") / f"fold{split}_{{pth.name}}"
    shutil.copy(pth, dest)
    print("saved", dest, dest.stat().st_size, "bytes", flush=True)
'''


def push_train_kernel(staging, user, competition, split, epochs, batch_size,
                      max_iters):
    """Push the embryo-disjoint training kernel for one fold."""
    kdir = staging.parent / "train_kernel"
    if kdir.exists():
        shutil.rmtree(kdir)
    kdir.mkdir(parents=True)

    max_iters_arg = (
        f'["--max-iters", "{max_iters}"]' if max_iters else "[]"
    )
    slug = f"{TRAIN_SLUG}-f{split}"
    (kdir / "train.py").write_text(
        TRAIN_TEMPLATE.format(
            competition=competition,
            pack_slug=PACK_SLUG,
            split=split,
            epochs=epochs,
            batch_size=batch_size,
            max_iters_arg=max_iters_arg,
        ),
        encoding="utf-8",
    )
    (kdir / "kernel-metadata.json").write_text(
        json.dumps(
            {
                "id": f"{user}/{slug}",
                "title": slug,
                "code_file": "train.py",
                "language": "python",
                "kernel_type": "script",
                "is_private": True,
                "enable_gpu": True,
                "enable_tpu": False,
                "enable_internet": False,
                "competition_sources": [competition],
                "dataset_sources": [f"{user}/{DATASET_SLUG}", PACK_SLUG],
                "kernel_sources": [],
                "model_sources": [],
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    r = _kaggle("kernels", "push", "-p", str(kdir),
                "--accelerator", "NvidiaTeslaT4")
    print((r.stdout or r.stderr).strip())
    if r.returncode != 0:
        raise SystemExit("training kernel push failed")
    return f"https://www.kaggle.com/code/{user}/{slug}"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("action", choices=["push", "train"])
    ap.add_argument("--config", default="")
    ap.add_argument("--message", default="update inference code")
    ap.add_argument("--split", type=int, default=0,
                    help="leave-one-embryo-out fold: 0 holds out 44b6, 1 holds out 6bba")
    ap.add_argument("--epochs", type=int, default=1)
    ap.add_argument("--batch-size", type=int, default=8)
    ap.add_argument("--max-iters", type=int, default=0,
                    help="cap iterations per epoch; use a small value to "
                         "calibrate throughput before spending real GPU hours")
    a = ap.parse_args()

    competition_ = json.loads(
        (REPO_ROOT / "competition.json").read_text(encoding="utf-8")
    )["slug"]
    if a.action == "train":
        user = _username()
        staging = Path(REPO_ROOT) / "artifacts" / "kaggle" / "dataset"
        cfg = load_config(a.config) if a.config else None
        stage_dataset(staging, user, cfg)
        push_dataset(staging, user, a.message)
        url = push_train_kernel(
            staging, user, competition_, a.split, a.epochs, a.batch_size,
            a.max_iters,
        )
        print(f"\ntraining kernel: {url}")
        return

    if not a.config:
        raise SystemExit("push needs --config")
    cfg = load_config(a.config)
    competition = json.loads(
        (REPO_ROOT / "competition.json").read_text(encoding="utf-8")
    )["slug"]
    user = _username()

    staging = Path(REPO_ROOT) / "artifacts" / "kaggle" / "dataset"
    stage_dataset(staging, user, cfg)
    push_dataset(staging, user, a.message)
    url = push_kernel(staging, user, cfg, competition)

    print(f"\nnotebook: {url}")
    print(
        "\nWait for it to finish, then click 'Submit to Competition' on that page.\n"
        "There is no public API endpoint for submitting a kernel to a competition,\n"
        "so that step is manual. Then record the score:\n"
        "  python -m src.submit --id <exp> --status"
    )


if __name__ == "__main__":
    main()
