"""Ship the inference code to Kaggle and push the submission notebook.

    python -m src.kernel push --config conf/baseline.yaml

This is a code competition, so the deliverable is a notebook Kaggle reruns against
a hidden test set. The workspace rule is that `src/` must be importable from a
Kaggle notebook and that notebooks are for looking, not for producing submissions.
Both are satisfied by shipping `src/` and `conf/` as a Kaggle **dataset** and
keeping the notebook to a handful of lines that import and call it.

The rerun has no internet, so the dataset is the only way code gets in. It also
means the notebook must not import anything absent from the Kaggle image:
`tracksdata`, `geff` and `zarr` are all missing, which is why `src.predict` avoids
them and `src.data` falls back to tensorstore.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

from src.config import REPO_ROOT, load_config

DATASET_SLUG = "cell-tracking-src"
KERNEL_SLUG = "cell-tracking-inference"

ARCHIVE_NAME = "cellmot_src.zip"

# The 50-epoch training of the architecture the organisers released. Public and
# freely available, so within the rules on pretrained models. It also carries the
# offline wheels, which is the only way tracksdata and pyscipopt reach a rerun
# with no internet.
PACK_SLUG = "srcA/biohub-tracking-support-pack-50ep-v1"

# Emitted only for a learned-detector config. The local-max path needs none of
# this and must keep booting on a CPU kernel with nothing installed.
UNET_PRELUDE = '''
def find_pack_dir():
    """Locate the support pack under /kaggle/input, whatever the mount layout."""
    for root, dirs, _ in os.walk("/kaggle/input"):
        if os.path.isfile(os.path.join(root, "repo", "scripts",
                                       "predict_unet_transformer.py")):
            return root
        dirs[:] = [d for d in dirs if d != "competitions"]
    raise SystemExit("support pack not attached: expected " + PACK_SLUG)


PACK = find_pack_dir()
print("pack dir:", PACK)
os.environ["CELLMOT_PACK_DIR"] = PACK

# No internet in the rerun, so dependencies come from the pack's own wheels.
import subprocess

# ilpy is listed explicitly rather than left to resolve as a dependency of
# tracksdata. The ILP linker fails without it, and a resolver that quietly
# decides it is optional would surface as a crash 3 hours into a 12 hour rerun.
subprocess.run(
    ["pip", "install", "--no-index", "--find-links", os.path.join(PACK, "wheels"),
     "tracksdata", "zarr>=3.0.10", "pyscipopt", "ilpy"],
    check=True,
)

# Fail now, in the first seconds, rather than after inference has run. A rerun
# that dies at the linking step has already spent the GPU hours.
import importlib

for _mod in ("tracksdata", "ilpy", "pyscipopt"):
    importlib.import_module(_mod)
print("solver imports ok")
'''

NOTEBOOK_TEMPLATE = '''"""Inference for {competition}. Generated by src/kernel.py, do not edit here.

Config: {config_name} ({config_hash})
"""

import os
import sys

PACK_SLUG = "{pack_slug}"

# The code is uploaded as a zip, which Kaggle expands on ingest, so the dataset
# root already holds src/ and conf/ as directories and can go straight on the
# path. An attached dataset is the only way code gets in: the rerun has no
# internet, so there is no installing anything.
def find_code_dir():
    """Locate the directory holding src/predict.py under /kaggle/input.

    The mount layout is not stable across Kaggle's own conventions: datasets have
    turned up at both /kaggle/input/<slug> and /kaggle/input/datasets/<user>/<slug>.
    Searching for the file we actually need is immune to that, and to anyone
    renaming the dataset later.
    """
    candidates = [
        "/kaggle/input/{dataset_slug}",
        "/kaggle/input/datasets/{user}/{dataset_slug}",
    ]
    for path in candidates:
        if os.path.isfile(os.path.join(path, "src", "predict.py")):
            return path
    for root, dirs, _ in os.walk("/kaggle/input"):
        if os.path.isfile(os.path.join(root, "src", "predict.py")):
            return root
        # The competition data is tens of thousands of files; never descend it.
        dirs[:] = [d for d in dirs if d != "competitions"]
    raise SystemExit(
        "could not find src/predict.py under /kaggle/input. "
        "Is the code dataset attached to this notebook?"
    )


CODE = find_code_dir()
print("code dir:", CODE)
sys.path.insert(0, CODE)

os.environ.setdefault(
    "CELLMOT_DATA_DIR",
    "/kaggle/input/competitions/{competition}",
)

{prelude}
from src.predict import run

run(
    config_path=os.path.join(CODE, "conf", "{config_file}"),
    out_path="/kaggle/working/submission.csv",
)
'''


def _kaggle(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, "-m", "kaggle", *args], capture_output=True, text=True
    )


def _username() -> str:
    """The account name, taken from whatever credential form is configured."""
    from kaggle.api.kaggle_api_extended import KaggleApi

    api = KaggleApi()
    api.authenticate()
    name = (getattr(api, "config_values", {}) or {}).get("username")
    if name:
        return name
    # Access-token auth does not expose the username locally, so ask the API.
    r = _kaggle("config", "view")
    for line in r.stdout.splitlines():
        if "username" in line.lower():
            return line.split(":")[-1].strip()
    raise SystemExit("could not determine the Kaggle username")


def stage_dataset(staging: Path, user: str, cfg) -> Path:
    """Zip src/ and conf/ into a staging dir with dataset metadata.

    A single zip at the dataset root, because Kaggle datasets flatten directories
    and a package needs its tree intact. `src/metrics.py` is excluded on purpose:
    it imports tracksdata, which is not installed on Kaggle, and nothing in the
    inference path should be able to reach it.
    """
    if staging.exists():
        shutil.rmtree(staging)
    staging.mkdir(parents=True)

    with zipfile.ZipFile(
        staging / ARCHIVE_NAME, "w", zipfile.ZIP_DEFLATED
    ) as zf:
        for name in sorted(os.listdir(REPO_ROOT / "src")):
            if name.endswith(".py") and name != "metrics.py":
                zf.write(REPO_ROOT / "src" / name, f"src/{name}")
        for name in sorted(os.listdir(REPO_ROOT / "conf")):
            if name.endswith((".yaml", ".yml")):
                zf.write(REPO_ROOT / "conf" / name, f"conf/{name}")
        # The leave-one-embryo-out splits, needed by a training kernel. Without
        # this file the reference trainer silently falls back to its seeded
        # 90/10 shuffle over all 199 videos, which puts crops of the same embryo
        # on both sides and is the exact measurement the retrain exists to
        # avoid. A missing file must therefore be loud, and it is checked for in
        # the training template rather than left to fail quietly here.
        for split_name in ("dataset_splits.json", "leak_splits.json"):
            splits = REPO_ROOT / "data" / "meta" / split_name
            if splits.exists():
                zf.write(splits, f"meta/{split_name}")

    (staging / "dataset-metadata.json").write_text(
        json.dumps(
            {
                "title": DATASET_SLUG,
                "id": f"{user}/{DATASET_SLUG}",
                "licenses": [{"name": "CC0-1.0"}],
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    return staging


def push_dataset(staging: Path, user: str, message: str) -> None:
    exists = _kaggle("datasets", "status", f"{user}/{DATASET_SLUG}").returncode == 0
    if exists:
        print(f"updating dataset {user}/{DATASET_SLUG}")
        r = _kaggle("datasets", "version", "-p", str(staging), "-m", message)
    else:
        print(f"creating dataset {user}/{DATASET_SLUG}")
        r = _kaggle("datasets", "create", "-p", str(staging))
    print((r.stdout or r.stderr).strip())
    if r.returncode != 0:
        raise SystemExit("dataset push failed")


def _is_unet(cfg) -> bool:
    """A learned-detector config needs a GPU, the pack, and its wheels."""
    return str((cfg.detect or {}).get("backend", "localmax")) == "unet"


def push_kernel(staging: Path, user: str, cfg, competition: str,
                tag: str = "") -> str:
    """Push the inference kernel, optionally under a suffixed slug.

    One fixed slug means a second config overwrites the first, so measuring three
    arms costs three sequential runs plus three waits. A suffix lets them run at
    once, which matters because a code competition scores the rerun rather than
    the notebook and the turnaround is hours. The suffix is part of the slug, so
    each arm keeps its own version history and its own logs.
    """
    slug = f"{KERNEL_SLUG}-{tag}" if tag else KERNEL_SLUG
    kdir = staging.parent / ("kernel-" + tag if tag else "kernel")
    if kdir.exists():
        shutil.rmtree(kdir)
    kdir.mkdir(parents=True)

    (kdir / "inference.py").write_text(
        NOTEBOOK_TEMPLATE.format(
            competition=competition,
            config_name=cfg.name,
            config_hash=cfg.hash(),
            config_file=Path(cfg.path).name,
            dataset_slug=DATASET_SLUG,
            archive=ARCHIVE_NAME,
            user=user,
            pack_slug=PACK_SLUG,
            prelude=UNET_PRELUDE if _is_unet(cfg) else "",
        ),
        encoding="utf-8",
    )
    (kdir / "kernel-metadata.json").write_text(
        json.dumps(
            {
                "id": f"{user}/{slug}",
                "title": slug,
                "code_file": "inference.py",
                "language": "python",
                "kernel_type": "script",
                "is_private": True,
                "enable_gpu": _is_unet(cfg),
                "enable_tpu": False,
                # Must stay false: the rerun disables internet, and a kernel that
                # only works with it on will fail exactly when it matters.
                "enable_internet": False,
                "competition_sources": [competition],
                "dataset_sources": (
                    [f"{user}/{DATASET_SLUG}"]
                    + ([PACK_SLUG] if _is_unet(cfg) else [])
                ),
                "kernel_sources": [],
                "model_sources": [],
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    # `enable_gpu` alone gets a P100, and this competition refuses to accept a
    # submission from a P100 notebook ("Your Notebook cannot use P100 GPUs in
    # this competition"). The accelerator is not a metadata field, so it has to
    # be passed on the push. Valid values: NvidiaTeslaT4, NvidiaTeslaP100,
    # Tpu1VmV38.
    push_args = ["kernels", "push", "-p", str(kdir)]
    if _is_unet(cfg):
        push_args += ["--accelerator", "NvidiaTeslaT4"]
    r = _kaggle(*push_args)
    out = (r.stdout or "") + (r.stderr or "")
    print(out.strip())
    # The CLI exits 0 on a refused push and reports the reason on stdout, so
    # the return code alone is not enough. This was found on 2026-08-28, when
    # "Maximum batch GPU session count of 2 reached" was printed and the pusher
    # then went on to print a notebook URL for a kernel that did not exist.
    # A push that failed must look like a failure.
    if r.returncode != 0 or "error" in out.lower():
        raise SystemExit(f"kernel push failed: {out.strip() or 'no output'}")
    return f"https://www.kaggle.com/code/{user}/{slug}"



CACHE_SLUG = "cell-tracking-cache"

CACHE_TEMPLATE = r'''"""Build the screening graph cache on a T4. Generated by src/kernel.py.

Detections and edge affinities for the {n_samples} videos the support pack held
out of its own training, at det_threshold {det_threshold}, TTA over {views}
views, candidates gated at {gate_um} um.

Why this runs on Kaggle at all, when every other screen in this repo runs
locally. Eight-view TTA costs 6.8 times a plain forward pass, measured on one
sample at six frames, and the plain cache is already about 70 minutes of local
CPU. That makes it an overnight job here against a couple of hours on a T4. The
cache is the only expensive artifact; once it lands, every calibration arm that
reads it is graph surgery and runs locally for free.

The gate is deliberately wide. Narrowing a cached candidate set gives exactly the
set that gating at that value would have produced, because the gate is a pure
distance filter applied after the probabilities were computed, so one wide cache
serves every narrower arm. Baking a narrow gate in here would bake in a setting
that is itself under test.

Output is one npz per sample under /kaggle/working, in the format
`src/graphcache.py` defines, which is the same format the local builder writes.
Two writers of one binary format is why that module exists.
"""

import json
import os
import sys
import time

PACK_SLUG = "{pack_slug}"


def find_code_dir():
    candidates = [
        "/kaggle/input/{dataset_slug}",
        "/kaggle/input/datasets/{user}/{dataset_slug}",
    ]
    for path in candidates:
        if os.path.isfile(os.path.join(path, "src", "graphcache.py")):
            return path
    for root, dirs, _ in os.walk("/kaggle/input"):
        if os.path.isfile(os.path.join(root, "src", "graphcache.py")):
            return root
        dirs[:] = [d for d in dirs if d != "competitions"]
    raise SystemExit("could not find src/graphcache.py under /kaggle/input")


CODE = find_code_dir()
print("code dir:", CODE, flush=True)
sys.path.insert(0, CODE)

os.environ.setdefault(
    "CELLMOT_DATA_DIR",
    "/kaggle/input/competitions/{competition}",
)

{prelude}
import numpy as np
import torch

from src.config import resolve_data_dir
from src.graphcache import HELDOUT, cache_path, save_cache
from src.data import Image
from src.unet import detect_and_score_sequence, load_detector

OUT = "/kaggle/working"
TRAIN = os.path.join(str(resolve_data_dir()), "train")
print("train dir:", TRAIN, flush=True)
if not os.path.isdir(TRAIN):
    raise SystemExit(
        "train directory not found at " + TRAIN + ". Under /kaggle/input: "
        + repr(sorted(os.listdir("/kaggle/input")))
    )

print("cuda available:", torch.cuda.is_available(), flush=True)
if not torch.cuda.is_available():
    # Falling back to CPU here would silently turn a two hour run into one that
    # cannot finish inside the twelve hour limit, and the output would be a
    # partial cache that looks complete until a screen reads it.
    raise SystemExit("no GPU visible, refusing to build the cache on CPU")

bundle = load_detector(None, "cuda")
print("model loaded, window", bundle[1], "downsample", bundle[2], flush=True)

manifest = []
t_start = time.time()
for idx, sample in enumerate(HELDOUT, 1):
    out = cache_path(OUT, sample)
    zarr_path = os.path.join(TRAIN, sample + ".zarr")
    if not os.path.isdir(zarr_path):
        raise SystemExit("missing sample " + zarr_path)
    t0 = time.time()
    dets, affs = detect_and_score_sequence(
        zarr_path, model=bundle,
        det_threshold={det_threshold},
        pool_kernel_um={pool_kernel_um},
        det_tta={det_tta},
        det_tta_views={views},
        device="cuda",
        edge_activation="softmax",
        edge_threshold={edge_threshold},
        max_link_um={gate_um},
    )
    scale = Image(zarr_path).scale
    tmp = out + ".tmp.npz"
    save_cache(tmp, dets, affs, scale)
    os.replace(tmp, out)
    n_nodes = int(sum(d.shape[0] for d in dets))
    n_cand = int(sum(a["i"].size for a in affs))
    secs = time.time() - t0
    manifest.append({{"sample": sample, "nodes": n_nodes,
                      "candidates": n_cand, "seconds": round(secs, 1)}})
    print("[%d/%d] %s  %.1f min  %d nodes  %d candidates  (elapsed %.1f min)"
          % (idx, len(HELDOUT), sample, secs / 60, n_nodes, n_cand,
             (time.time() - t_start) / 60), flush=True)

with open(os.path.join(OUT, "manifest.json"), "w") as fh:
    json.dump({{"det_threshold": {det_threshold}, "det_tta": {det_tta},
               "det_tta_views": {views}, "gate_um": {gate_um},
               "edge_threshold": {edge_threshold},
               "pool_kernel_um": {pool_kernel_um},
               "total_minutes": round((time.time() - t_start) / 60, 1),
               "samples": manifest}}, fh, indent=2)
print("\ndone, %d samples in %.1f min"
      % (len(manifest), (time.time() - t_start) / 60), flush=True)
'''


def push_cache_kernel(staging: Path, user: str, competition: str,
                      det_threshold: float, views: int, gate_um: float,
                      edge_threshold: float, pool_kernel_um: float,
                      tag: str = "") -> str:
    """Push the GPU kernel that builds a screening cache.

    Separate from `push_kernel` because it produces an artifact rather than a
    submission: there is no CSV, nothing to submit to the competition, and the
    output is downloaded with `kaggle kernels output` and dropped into
    `data/meta/`. It still needs the pack, the wheels and a T4, so it reuses the
    same prelude and the same accelerator argument.
    """
    slug = f"{CACHE_SLUG}-{tag}" if tag else CACHE_SLUG
    kdir = staging.parent / ("cache-" + tag if tag else "cache")
    if kdir.exists():
        shutil.rmtree(kdir)
    kdir.mkdir(parents=True)

    from src.graphcache import HELDOUT

    (kdir / "build_cache.py").write_text(
        CACHE_TEMPLATE.format(
            competition=competition,
            dataset_slug=DATASET_SLUG,
            user=user,
            pack_slug=PACK_SLUG,
            prelude=UNET_PRELUDE,
            n_samples=len(HELDOUT),
            det_threshold=det_threshold,
            det_tta=bool(views and views > 1),
            views=int(views),
            gate_um=gate_um,
            edge_threshold=edge_threshold,
            pool_kernel_um=pool_kernel_um,
        ),
        encoding="utf-8",
    )
    (kdir / "kernel-metadata.json").write_text(
        json.dumps(
            {
                "id": f"{user}/{slug}",
                "title": slug,
                "code_file": "build_cache.py",
                "language": "python",
                "kernel_type": "script",
                "is_private": True,
                "enable_gpu": True,
                "enable_tpu": False,
                "enable_internet": False,
                "competition_sources": [competition],
                "dataset_sources": [f"{user}/{DATASET_SLUG}", PACK_SLUG],
                "kernel_sources": [],
                "model_sources": [],
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    r = _kaggle("kernels", "push", "-p", str(kdir),
                "--accelerator", "NvidiaTeslaT4")
    out = (r.stdout or "") + (r.stderr or "")
    print(out.strip())
    if r.returncode != 0 or "error" in out.lower():
        raise SystemExit(f"cache kernel push failed: {out.strip() or 'no output'}")
    return f"https://www.kaggle.com/code/{user}/{slug}"


TRAIN_SLUG = "cell-tracking-train"

TRAIN_TEMPLATE = '''"""Embryo-disjoint training for {competition}. Generated by src/kernel.py.

Fold {split} of leave-one-embryo-out. Do not edit here.

Why from scratch and not from the support pack's weights. The pack was trained on
180 of the 199 training videos, drawn from BOTH embryos. Initialising from it
would put the held-out embryo's images into the model before the first step, which
is the leak this whole run exists to remove. `--unet-weights` is therefore not
passed, and that is deliberate rather than an omission.
"""

import json
import os
import subprocess
import sys
import time

PACK_SLUG = "{pack_slug}"


def find_pack_dir():
    for root, dirs, _ in os.walk("/kaggle/input"):
        if os.path.isdir(os.path.join(root, "repo", "scripts")):
            return root
        dirs[:] = [d for d in dirs if d != "competitions"]
    raise SystemExit("support pack not attached: expected " + PACK_SLUG)


SPLITS_NAME = "{splits_name}"


def find_code_dir():
    for root, dirs, _ in os.walk("/kaggle/input"):
        if os.path.isfile(os.path.join(root, "meta", SPLITS_NAME)):
            return root
        dirs[:] = [d for d in dirs if d != "competitions"]
    raise SystemExit("code dataset with meta/" + SPLITS_NAME + " not attached")


PACK = find_pack_dir()
CODE = find_code_dir()
SPLITS = os.path.join(CODE, "meta", SPLITS_NAME)
print("pack:", PACK, flush=True)
print("code:", CODE, flush=True)

subprocess.run(
    ["pip", "install", "--no-index", "--find-links", os.path.join(PACK, "wheels"),
     "tracksdata", "zarr>=3.0.10", "pyscipopt", "ilpy"],
    check=True,
)

sys.path.insert(0, os.path.join(PACK, "repo", "src"))
sys.path.insert(0, os.path.join(PACK, "repo", "scripts"))

DATA = "/kaggle/input/competitions/{competition}/train"
os.environ["CELLMOT_DATA_DIR"] = "/kaggle/input/competitions/{competition}"

# Guard the thing that silently invalidates the run. The trainer accepts a
# missing splits file by falling back to random.Random(0) over all videos, so an
# absent or malformed file would produce a plausible model measuring the wrong
# thing.
folds = json.loads(open(SPLITS).read())
fold = [f for f in folds if int(f["split"]) == {split}]
if not fold:
    raise SystemExit("no fold {split} in " + SPLITS)
fold = fold[0]
train_stems, test_stems = fold["train"], fold["test"]
emb = lambda n: n.split("_")[0]
overlap = {{emb(a) for a in train_stems}} & {{emb(b) for b in test_stems}}
leaked_videos = set(train_stems) & set(test_stems)
if leaked_videos:
    # Never acceptable under any design: the same video on both sides.
    raise SystemExit(f"{{len(leaked_videos)}} videos are in both train and test")
if {require_disjoint} and overlap:
    # The reference trainer falls back to a seeded 90/10 over all 199 videos when
    # its splits file is missing, which shares embryos across the split. A run
    # that silently did that would look fine and measure the wrong thing.
    raise SystemExit(f"fold {split} should be embryo-disjoint but shares {{overlap}}")
print(f"fold {split} shares embryos with its test set: {{sorted(overlap)}}",
      flush=True)

# Drop any video the mount does not actually carry. The reference loader raises
# FileNotFoundError on the first missing image and takes the whole run with it,
# which cost a 48 minute job for one absent file. A split is a list of names
# written on another machine, so it is a claim about the mount rather than a
# fact, and it gets checked here.
def _present(stem):
    return os.path.isdir(os.path.join(DATA, stem + ".zarr"))

missing_train = [s for s in train_stems if not _present(s)]
missing_test = [s for s in test_stems if not _present(s)]
if missing_train or missing_test:
    print(f"WARNING: {{len(missing_train)}} train and {{len(missing_test)}} test "
          f"videos are not on this mount and are dropped: "
          f"{{(missing_train + missing_test)[:5]}}", flush=True)
    train_stems = [s for s in train_stems if _present(s)]
    test_stems = [s for s in test_stems if _present(s)]
    if not train_stems or not test_stems:
        raise SystemExit("a whole side of the split is missing; nothing to train on")
    # Rewrite the splits file so the trainer reads the filtered lists. It takes a
    # path, not a list, so filtering in memory here would have no effect.
    SPLITS = "/kaggle/working/splits_filtered.json"
    with open(SPLITS, "w") as fh:
        json.dump([{{"split": {split}, "train": train_stems, "test": test_stems}}],
                  fh)
    print(f"filtered splits written to {{SPLITS}}: {{len(train_stems)}} train, "
          f"{{len(test_stems)}} test", flush=True)
print(f"fold {split}: {{len(train_stems)}} train videos "
      f"({{sorted({{emb(a) for a in train_stems}})}}), "
      f"{{len(test_stems)}} test ({{sorted({{emb(b) for b in test_stems}})}})",
      flush=True)

import torch
print("cuda:", torch.cuda.is_available(), torch.cuda.get_device_name(0)
      if torch.cuda.is_available() else "", flush=True)

# `--single-gpu` is deliberately NOT passed. Kaggle's T4 allocation reports
# "visible CUDA GPUs: 2" and the trainer will split the UNet across both with
# DataParallel, which both halves the step time and halves per-GPU memory. The
# first calibration passed --single-gpu and died at iteration 3 with a CUDA OOM
# at batch 8: 4.00 GiB requested against 3.29 GiB free on the one GPU it was
# using. Batch size is also lowered, since the OOM had headroom of well under a
# factor of two.
sys.argv = [
    "train_unet_transformer.py",
    "--data-dir", DATA,
    "--splits", SPLITS,
    "--split", "{split}",
    "--epochs", "{epochs}",
    "--batch-size", "{batch_size}",
    "--num-workers", "2",
    "--window-size", "2",
    "--downsample", "1,4,4",
    "--pool-kernel-um", "5.0",
] + ({max_iters_arg})

t0 = time.time()
import train_unet_transformer
from pathlib import Path

# The trainer writes its checkpoint to `dataspec.WEIGHTS_PATH`, which is derived
# from the location of dataspec.py itself and therefore lands inside the pack
# mount. That mount is read-only on Kaggle, so the run dies at the first save
# with OSError errno 30, after loading every video. There is no environment
# variable for it, unlike the data dir, so the module global is rebound here.
# `train_unet_transformer` does `from dataspec import WEIGHTS_PATH`, so its own
# global is the one that has to change; patching dataspec after import would
# have no effect.
train_unet_transformer.WEIGHTS_PATH = Path("/kaggle/working/weights")
print("weights dir:", train_unet_transformer.WEIGHTS_PATH, flush=True)

train_unet_transformer.main()
print("total minutes:", round((time.time() - t0) / 60, 1), flush=True)

# The checkpoint is already under /kaggle/working, which is what Kaggle keeps as
# the kernel's output. Copy it to the root under a fold-tagged name so the two
# folds cannot collide when both are attached to an inference kernel later.
import shutil

found = sorted(Path("/kaggle/working/weights").rglob("edge_predictor_best.pth"))
if not found:
    print("WARNING: no checkpoint written", flush=True)
for pth in found:
    dest = Path("/kaggle/working") / ("fold{split}_" + pth.name)
    shutil.copy(pth, dest)
    print("saved", dest, dest.stat().st_size, "bytes", flush=True)
'''


def push_train_kernel(staging, user, competition, split, epochs, batch_size,
                      max_iters, splits_name="dataset_splits.json",
                      require_disjoint=True, tag="f"):
    """Push a training kernel for one fold of one splits file."""
    kdir = staging.parent / "train_kernel"
    if kdir.exists():
        shutil.rmtree(kdir)
    kdir.mkdir(parents=True)

    max_iters_arg = (
        f'["--max-iters", "{max_iters}"]' if max_iters else "[]"
    )
    slug = f"{TRAIN_SLUG}-{tag}{split}"
    (kdir / "train.py").write_text(
        TRAIN_TEMPLATE.format(
            competition=competition,
            pack_slug=PACK_SLUG,
            split=split,
            epochs=epochs,
            batch_size=batch_size,
            max_iters_arg=max_iters_arg,
            splits_name=splits_name,
            require_disjoint=bool(require_disjoint),
        ),
        encoding="utf-8",
    )
    (kdir / "kernel-metadata.json").write_text(
        json.dumps(
            {
                "id": f"{user}/{slug}",
                "title": slug,
                "code_file": "train.py",
                "language": "python",
                "kernel_type": "script",
                "is_private": True,
                "enable_gpu": True,
                "enable_tpu": False,
                "enable_internet": False,
                "competition_sources": [competition],
                "dataset_sources": [f"{user}/{DATASET_SLUG}", PACK_SLUG],
                "kernel_sources": [],
                "model_sources": [],
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    r = _kaggle("kernels", "push", "-p", str(kdir),
                "--accelerator", "NvidiaTeslaT4")
    print((r.stdout or r.stderr).strip())
    if r.returncode != 0:
        raise SystemExit("training kernel push failed")
    return f"https://www.kaggle.com/code/{user}/{slug}"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("action", choices=["push", "train", "cache"])
    ap.add_argument("--config", default="")
    ap.add_argument("--message", default="update inference code")
    ap.add_argument("--split", type=int, default=0,
                    help="leave-one-embryo-out fold: 0 holds out 44b6, 1 holds out 6bba")
    ap.add_argument("--epochs", type=int, default=1)
    ap.add_argument("--batch-size", type=int, default=8)
    ap.add_argument("--splits-name", default="dataset_splits.json",
                    help="which splits file in the code dataset to train against")
    ap.add_argument("--allow-shared-embryo", action="store_true",
                    help="permit a fold whose train and test share an embryo. "
                         "Only for the matched leak measurement, where sharing "
                         "is the variable under test")
    ap.add_argument("--tag", default="f",
                    help="training kernel slug suffix, so runs do not overwrite "
                         "each other")
    ap.add_argument("--kernel-tag", default="",
                    help="inference kernel slug suffix, so several arms can run "
                         "at once. Empty keeps the original slug, which is what "
                         "every submission before 2026-08-27 used")
    ap.add_argument("--det-threshold", type=float, default=0.99,
                    help="cache action: detection threshold. Must match the "
                         "cache it will be compared against, since the edge "
                         "head's softmax normalises over the nodes present and "
                         "the threshold is therefore a cache key")
    ap.add_argument("--views", type=int, default=8, choices=(1, 4, 8),
                    help="cache action: size of the dihedral TTA group. 1 is no "
                         "TTA at all")
    ap.add_argument("--gate-um", type=float, default=20.0,
                    help="cache action: candidate gate. Wide on purpose so every "
                         "narrower arm can share one cache")
    ap.add_argument("--edge-threshold", type=float, default=0.05)
    ap.add_argument("--pool-kernel-um", type=float, default=5.0)
    ap.add_argument("--max-iters", type=int, default=0,
                    help="cap iterations per epoch; use a small value to "
                         "calibrate throughput before spending real GPU hours")
    a = ap.parse_args()

    competition_ = json.loads(
        (REPO_ROOT / "competition.json").read_text(encoding="utf-8")
    )["slug"]
    if a.action == "cache":
        user = _username()
        staging = Path(REPO_ROOT) / "artifacts" / "kaggle" / "dataset"
        stage_dataset(staging, user, None)
        push_dataset(staging, user, a.message)
        url = push_cache_kernel(
            staging, user, competition_, a.det_threshold, a.views,
            a.gate_um, a.edge_threshold, a.pool_kernel_um, tag=a.kernel_tag,
        )
        print(f"\ncache kernel: {url}")
        print(
            "\nWhen it finishes, pull the npz files down with:\n"
            f"  python -m kaggle kernels output {user}/"
            f"{CACHE_SLUG + ('-' + a.kernel_tag if a.kernel_tag else '')}"
            " -p data/meta/graph_cache_t099_tta8\n"
            "then screen against it with --cache pointing at that directory."
        )
        return

    if a.action == "train":
        user = _username()
        staging = Path(REPO_ROOT) / "artifacts" / "kaggle" / "dataset"
        cfg = load_config(a.config) if a.config else None
        stage_dataset(staging, user, cfg)
        push_dataset(staging, user, a.message)
        url = push_train_kernel(
            staging, user, competition_, a.split, a.epochs, a.batch_size,
            a.max_iters, splits_name=a.splits_name,
            require_disjoint=not a.allow_shared_embryo, tag=a.tag,
        )
        print(f"\ntraining kernel: {url}")
        return

    if not a.config:
        raise SystemExit("push needs --config")
    cfg = load_config(a.config)
    competition = json.loads(
        (REPO_ROOT / "competition.json").read_text(encoding="utf-8")
    )["slug"]
    user = _username()

    staging = Path(REPO_ROOT) / "artifacts" / "kaggle" / "dataset"
    stage_dataset(staging, user, cfg)
    push_dataset(staging, user, a.message)
    url = push_kernel(staging, user, cfg, competition, tag=a.kernel_tag)

    print(f"\nnotebook: {url}")
    print(
        "\nWait for it to finish, then click 'Submit to Competition' on that page.\n"
        "There is no public API endpoint for submitting a kernel to a competition,\n"
        "so that step is manual. Then record the score:\n"
        "  python -m src.submit --id <exp> --status"
    )


if __name__ == "__main__":
    main()
