"""Ship the inference code to Kaggle and push the submission notebook.

    python -m src.kernel push --config conf/baseline.yaml

This is a code competition, so the deliverable is a notebook Kaggle reruns against
a hidden test set. The workspace rule is that `src/` must be importable from a
Kaggle notebook and that notebooks are for looking, not for producing submissions.
Both are satisfied by shipping `src/` and `conf/` as a Kaggle **dataset** and
keeping the notebook to a handful of lines that import and call it.

The rerun has no internet, so the dataset is the only way code gets in. It also
means the notebook must not import anything absent from the Kaggle image:
`tracksdata`, `geff` and `zarr` are all missing, which is why `src.predict` avoids
them and `src.data` falls back to tensorstore.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

from src.config import REPO_ROOT, load_config

DATASET_SLUG = "cell-tracking-src"
KERNEL_SLUG = "cell-tracking-inference"

ARCHIVE_NAME = "cellmot_src.zip"

NOTEBOOK_TEMPLATE = '''"""Inference for {competition}. Generated by src/kernel.py, do not edit here.

Config: {config_name} ({config_hash})
"""

import os
import sys

# The code is uploaded as a zip, which Kaggle expands on ingest, so the dataset
# root already holds src/ and conf/ as directories and can go straight on the
# path. An attached dataset is the only way code gets in: the rerun has no
# internet, so there is no installing anything.
def find_code_dir():
    """Locate the directory holding src/predict.py under /kaggle/input.

    The mount layout is not stable across Kaggle's own conventions: datasets have
    turned up at both /kaggle/input/<slug> and /kaggle/input/datasets/<user>/<slug>.
    Searching for the file we actually need is immune to that, and to anyone
    renaming the dataset later.
    """
    candidates = [
        "/kaggle/input/{dataset_slug}",
        "/kaggle/input/datasets/{user}/{dataset_slug}",
    ]
    for path in candidates:
        if os.path.isfile(os.path.join(path, "src", "predict.py")):
            return path
    for root, dirs, _ in os.walk("/kaggle/input"):
        if os.path.isfile(os.path.join(root, "src", "predict.py")):
            return root
        # The competition data is tens of thousands of files; never descend it.
        dirs[:] = [d for d in dirs if d != "competitions"]
    raise SystemExit(
        "could not find src/predict.py under /kaggle/input. "
        "Is the code dataset attached to this notebook?"
    )


CODE = find_code_dir()
print("code dir:", CODE)
sys.path.insert(0, CODE)

os.environ.setdefault(
    "CELLMOT_DATA_DIR",
    "/kaggle/input/competitions/{competition}",
)

from src.predict import run

run(
    config_path=os.path.join(CODE, "conf", "{config_file}"),
    out_path="/kaggle/working/submission.csv",
)
'''


def _kaggle(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, "-m", "kaggle", *args], capture_output=True, text=True
    )


def _username() -> str:
    """The account name, taken from whatever credential form is configured."""
    from kaggle.api.kaggle_api_extended import KaggleApi

    api = KaggleApi()
    api.authenticate()
    name = (getattr(api, "config_values", {}) or {}).get("username")
    if name:
        return name
    # Access-token auth does not expose the username locally, so ask the API.
    r = _kaggle("config", "view")
    for line in r.stdout.splitlines():
        if "username" in line.lower():
            return line.split(":")[-1].strip()
    raise SystemExit("could not determine the Kaggle username")


def stage_dataset(staging: Path, user: str, cfg) -> Path:
    """Zip src/ and conf/ into a staging dir with dataset metadata.

    A single zip at the dataset root, because Kaggle datasets flatten directories
    and a package needs its tree intact. `src/metrics.py` is excluded on purpose:
    it imports tracksdata, which is not installed on Kaggle, and nothing in the
    inference path should be able to reach it.
    """
    if staging.exists():
        shutil.rmtree(staging)
    staging.mkdir(parents=True)

    with zipfile.ZipFile(
        staging / ARCHIVE_NAME, "w", zipfile.ZIP_DEFLATED
    ) as zf:
        for name in sorted(os.listdir(REPO_ROOT / "src")):
            if name.endswith(".py") and name != "metrics.py":
                zf.write(REPO_ROOT / "src" / name, f"src/{name}")
        for name in sorted(os.listdir(REPO_ROOT / "conf")):
            if name.endswith((".yaml", ".yml")):
                zf.write(REPO_ROOT / "conf" / name, f"conf/{name}")

    (staging / "dataset-metadata.json").write_text(
        json.dumps(
            {
                "title": DATASET_SLUG,
                "id": f"{user}/{DATASET_SLUG}",
                "licenses": [{"name": "CC0-1.0"}],
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    return staging


def push_dataset(staging: Path, user: str, message: str) -> None:
    exists = _kaggle("datasets", "status", f"{user}/{DATASET_SLUG}").returncode == 0
    if exists:
        print(f"updating dataset {user}/{DATASET_SLUG}")
        r = _kaggle("datasets", "version", "-p", str(staging), "-m", message)
    else:
        print(f"creating dataset {user}/{DATASET_SLUG}")
        r = _kaggle("datasets", "create", "-p", str(staging))
    print((r.stdout or r.stderr).strip())
    if r.returncode != 0:
        raise SystemExit("dataset push failed")


def push_kernel(staging: Path, user: str, cfg, competition: str) -> str:
    kdir = staging.parent / "kernel"
    if kdir.exists():
        shutil.rmtree(kdir)
    kdir.mkdir(parents=True)

    (kdir / "inference.py").write_text(
        NOTEBOOK_TEMPLATE.format(
            competition=competition,
            config_name=cfg.name,
            config_hash=cfg.hash(),
            config_file=Path(cfg.path).name,
            dataset_slug=DATASET_SLUG,
            archive=ARCHIVE_NAME,
            user=user,
        ),
        encoding="utf-8",
    )
    (kdir / "kernel-metadata.json").write_text(
        json.dumps(
            {
                "id": f"{user}/{KERNEL_SLUG}",
                "title": KERNEL_SLUG,
                "code_file": "inference.py",
                "language": "python",
                "kernel_type": "script",
                "is_private": True,
                "enable_gpu": False,
                "enable_tpu": False,
                # Must stay false: the rerun disables internet, and a kernel that
                # only works with it on will fail exactly when it matters.
                "enable_internet": False,
                "competition_sources": [competition],
                "dataset_sources": [f"{user}/{DATASET_SLUG}"],
                "kernel_sources": [],
                "model_sources": [],
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    r = _kaggle("kernels", "push", "-p", str(kdir))
    print((r.stdout or r.stderr).strip())
    if r.returncode != 0:
        raise SystemExit("kernel push failed")
    return f"https://www.kaggle.com/code/{user}/{KERNEL_SLUG}"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("action", choices=["push"])
    ap.add_argument("--config", required=True)
    ap.add_argument("--message", default="update inference code")
    a = ap.parse_args()

    cfg = load_config(a.config)
    competition = json.loads(
        (REPO_ROOT / "competition.json").read_text(encoding="utf-8")
    )["slug"]
    user = _username()

    staging = Path(REPO_ROOT) / "artifacts" / "kaggle" / "dataset"
    stage_dataset(staging, user, cfg)
    push_dataset(staging, user, a.message)
    url = push_kernel(staging, user, cfg, competition)

    print(f"\nnotebook: {url}")
    print(
        "\nWait for it to finish, then click 'Submit to Competition' on that page.\n"
        "There is no public API endpoint for submitting a kernel to a competition,\n"
        "so that step is manual. Then record the score:\n"
        "  python -m src.submit --id <exp> --status"
    )


if __name__ == "__main__":
    main()
